defaults: &defaults
  docker:
    - image: circleci/golang:1.8
  working_directory: /go/src/github.com/morikuni/dummy

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: install
          command: make install
      - run:
          name: init
          command: make init
      - run:
          name: test
          command: make test

